### ISSUE TITLE
error when importing SDL with GPUs into SDL Builder

### ISSUE THREAD

**Issue by gosuri** [akash-network/cloudmos#27]
I uploaded an SDL with GPUs and the builder threw an error.
<img width="894" alt="Screenshot 2023-10-10 at 7 40 28 PM" src="https://github.com/akash-network/cloudmos/assets/70293/a355132d-d77e-493b-b245-9a7099c9d598">

SDL for ref:

```
---
version: "2.0"
services:
  app:
    image: zjuuu/comfyui:0.5
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
    env:
      - "VAEURLS="
      - "MODELURLS="
      - "UPSCALEURLS="
      - "COMMANDLINE_ARGS=--listen --port 8080 --gpu-only"
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 6.0
        memory:
          size: 35Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
        storage:
          size: 50Gi
  placement:
    akash:
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1

```
